= Anwenderdokumentation

== 1. Einführung
Die Refugee-App wurde im Rahmen des Softwarepraktikums der TU Dresden von Studenten entwickelt.
Bei der Anwendung handelt es sich um ein Angebotsportal zum Suchen und Finden von Sachspenden und Freizeitsangeboten um den Austausch zwischen Flüchtlingen und Helfern
auch über Sprachgrenzen hinweg zu unterstützen. Dafür ermöglicht es das Einstellen und die themen- bzw. entfernungsbestimmte Suche nach Angeboten, 
die Möglichkeit der Kontaktaufnahme per Dialog sowie eine mehrsprachige Benutzeroberfläche.

== 2. Systemanforderungen

Die Anwendung ist sowohl für PCs als auch auf Mobilgeräten kompatibel.
Zur Nutzung der Anwendung ist ein Gerät mit Internetverbindung und einem Internetbrowser notwendig. 
Die beste Unterstützung aller Funktionen bietet der Google Chrome, eine Nutzung der App ist aber auch über andere Browser möglich.
Zur einfacheren und flüssigen Bedienung wird zusätzlich empfohlen JavaScript zu aktivieren.

=== 2.1 Server
Die Webanwendung soll auf PCs oder Servern mit 32Bit oder 64Bit-Prozessoren mit mind.
2 GB RAM laufen können. Als Zielsystem wird das Windows-Betriebssystem (ab Windows 7) unterstützt. Als Laufzeitumgebung kommt Oracle Java 8 zum Einsatz.
Eine dauerhafte Internetverbindung muss zur Verfügung stehen und die Anwendung muss über einem gültigen Googleaccount verfügen, 
um die Nutzung des Captchas sowie den Abruf der Nutzerkoordinaten zu ermöglichen.
 
== 3. Seitenfunktionalität- Kunde

=== 3.1 Login
Auf der Loginseite kann sich der Nutzer nach Aktivierung über den Link in der Anmeldungsmail mit seinen Nutzerdaten einloggen.
Bei falschen Eingaben oder fehlender Aktivierung wird eine Fehlermeldung ausgegeben.
Es existiert ein Link zur Registrierung.

=== 3.2 Registrierung
Diese Seite ermöglicht einem Nutzer einen neuen Account zu erstellen. Die vollständige Eingabe der Daten ist verpflichtend, 
zusätzlich existieren Formatvorlagen für die Postleihzahl (fünfstellige Ziffernfolge)und das Passwort(Zeichen lang,enthält Groß- und Kleinbuchstaben, Ziffern und Sonderzeichen).
Bei fehlerhaften Eingaben wird der User zurück auf die Seite geleitet und es wird eine Fehlermeldung angezeigt. Die eingegebenen Daten- bis auf das Passwort- bleiben erhalten.
Nach erfolgreicher Registrierung erhalt der Nutzer eine Email mit Aktivierungslink (als Link und Linkadresse).

=== 3.3 Index und Güter
Bei erfolgreichem Login gelangt der Nutzer dann auf die Startseite, wo die vorhandenen Güter und Aktivitäten angezeigt werden.
Wie auf jeder Seite ist die Navigation mit Suchfunktion (eingeschränkt nach Kategorie und/oder Entfernung) sowie eine Navigationsleite vorhanden.
Bei Anklicken der Güter wird auf die Seite des Gutes weitergeleitet, die zusätzliche Informationen und die Möglichkeit der Kontaktaufnahme bietet.
Der genaue Standort des Angebotes wird dabei aus Gründen der Nutzersicherheit nicht angezeigt, sondern lediglich der Name der Stadt. 

=== 3.4 Userdaten
Über den Link in der Navigation gelangt der Nutzer zu einer Übersicht der von ihm gespeicherten Daten und hat die Möglichkeit diese zu ändern.
Auch eine Deaktivierung des eigenen Nutzerkontos ist möglich.

=== 3.5 Angebote
Über das Feld "Angebot" in der Navigationsleite kann wahlweise ein Gut oder eine Aktivität erstellt werden.
Das Angebot wird dabei einer Kategorie zugeordnet, erhält einen Namen und eine Kurzbeschreibung und der User hat die Möglichkeit ein passendes Bild hochzuladen.
Als Standort des Angebotes wird dabei die Adresse des Users angenommen.
Über das Feld mit dem Nutzernamen kann unter "Meine angebotenen Güter" bzw. "Meine angebotenen Aktivitäten" die Liste der eigenen Angebote eingesehen und diese gelöscht oder geändert werden.

=== 3.6 Dialog
Über den Button im jeweiligen Angebot kann ein Dialog mit dem Nutzer der es eingestellt hat begonnen werden.
Hierbei stehen Textbausteine zur Auswahl und können mit den jeweiligen Informationen komplettiert werden.
Begonnene Dialoge können unter "Meine Dialoge" in der Navigationsleiste eingesehen werden.

== 4. Seitenfunktionalität- Admin
Die Registrierung eines Admin ist nicht möglich. 
Mit den vorhandenen Logindaten kann sich ein Admin einloggen.

=== 4.1 Nutzer
Der Admin kann sich über die Navigation die Nutzerübersicht anzeigen lassen und über die jeweiligen Links Nutzer bearbeiten und deaktivieren (bzw. deaktivierte Nutzer wieder aktivieren).
Die Seite verfügt auch über eine Suchfunktion um einzelne Nutzer bei ihrem Username zu finden.
Der Admin kann sämtliche Daten eines Nutzers außer dem Username ändern, auch die Herkunft, was dem Nutzer selbst nicht möglich ist.

=== 4.2 Angebote
In der Rolle des Admins lassen sich alle vorhandenen Angebote bearbeiten oder löschen.

=== 4.3 Dialog & Mehrsprachigkeit
Der Admin hat die Möglichkeit neue Dialogbausteine zu erstellen.
Auch das Erstellen neuer Sprachen und Templates ist möglich. 

== 5. Gruppe
* Mario Henze- Scrummaster, Dialog
* Kilian Heret- Registrierung, Mail, Captcha
* Friederike Kitzing- Userverwaltung, Koordinaten
* Ferdinand Lehmann- Bilder, mehrsprachiges Interface
* Lennart Schmidt- Frontend
* Alejandro Sánchez Aristizábal- Angebotsverwaltung

Server unter: http://refugee-app.tk/swt15w9/